sudo: required
dist: bionic

language: ruby
cache: bundler

if: tag IS blank

env:
  - TEST_GROUP="cucumber features/other_a/autocomplete.feature" TRY=0
  - TEST_GROUP="cucumber features/other_a/autocomplete.feature" TRY=1
  - TEST_GROUP="cucumber features/other_a/autocomplete.feature" TRY=2
  - TEST_GROUP="cucumber features/other_a/autocomplete.feature" TRY=3
  - TEST_GROUP="cucumber features/other_a/autocomplete.feature" TRY=4
  - TEST_GROUP="cucumber features/other_a/autocomplete.feature" TRY=5
  - TEST_GROUP="cucumber features/other_a/autocomplete.feature" TRY=6
  - TEST_GROUP="cucumber features/other_a/autocomplete.feature" TRY=7
  - TEST_GROUP="cucumber features/other_a/autocomplete.feature" TRY=8
  - TEST_GROUP="cucumber features/other_a/autocomplete.feature" TRY=9
  - TEST_GROUP="cucumber features/tags_and_wrangling/" TRY=0
  - TEST_GROUP="cucumber features/tags_and_wrangling/" TRY=1
  - TEST_GROUP="cucumber features/tags_and_wrangling/" TRY=2
  - TEST_GROUP="cucumber features/tags_and_wrangling/" TRY=3
  - TEST_GROUP="cucumber features/tags_and_wrangling/" TRY=4
  - TEST_GROUP="cucumber features/tags_and_wrangling/" TRY=5
  - TEST_GROUP="cucumber features/tags_and_wrangling/" TRY=6
  - TEST_GROUP="cucumber features/tags_and_wrangling/" TRY=7
  - TEST_GROUP="cucumber features/tags_and_wrangling/" TRY=8
  - TEST_GROUP="cucumber features/tags_and_wrangling/" TRY=9

services:
  - mysql
  - redis
  - memcached

before_install:
  - bash script/travis/ebook_converters.sh

before_script:
  - bash script/travis/configure.sh
  - bash script/travis/elasticsearch_upgrade.sh
  - bash script/travis/multiple_redis.sh
  - bash script/travis/mysql.sh

script:
  - export RAILS_ENV=test
  - export CUCUMBER_FORMAT=Ao3Cucumber::Formatter
  - bundle exec rake db:schema:load
  - bundle exec rake db:migrate
  - bundle exec "$TEST_GROUP"

after_failure:
  - tail -v -n +1 $TRAVIS_BUILD_DIR/tmp/capybara/*.html
